/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

/**
 *
 * @author user
 */

import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.table.DefaultTableModel;
public class Add_Appointment extends javax.swing.JFrame {

    Object[] myData = new Object[25];
    
    public Add_Appointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        timePicker1 = new com.github.lgooddatepicker.components.TimePicker();
        cmbCenter = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeople = new javax.swing.JTable();
        cmbPeople = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        cmbCenter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAdd.setText("Add");
        btnAdd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblPeople.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Phone Number", "Address", "IC/Passport No.", "Dose", "Date", "Time", "Center Code", "Center Name", "Center Address", "Vaccine", "Batch", "Dose", "Date", "Time", "Center Code", "Center Name", "Center Address", "Vaccine", "Batch"
            }
        ));
        tblPeople.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(tblPeople);

        cmbPeople.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Citizens", "Non-Citizens" }));
        cmbPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPeopleActionPerformed(evt);
            }
        });

        jLabel1.setText("Add Appointment  for Registered People");
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N

        jLabel2.setText("Please select a group:");
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel3.setText("Please selctc a date:");
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel4.setText("Please select a time:");
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel5.setText("Vaccination Center:");
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbPeople, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCenter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(642, 642, 642)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(timePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnAdd))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        
        // add Vaccination Center to combo box
        cmbCenter.removeAllItems();
        File file = new File("Vaccination_center.txt");
        
        try
        {
            
            Scanner Sc = new Scanner(file);
            while(Sc.hasNextLine())
            {
                String Line = Sc.nextLine();
                String[] Arr = Line.split(";");
                cmbCenter.addItem(Arr[1]);
                //write to jtable
            }
        }
        catch(FileNotFoundException ex)
        {
            
        }
        
        // add People to table
        
        FileOperation Fop = new FileOperation();
        Fop.ReadfromFile("");
    }//GEN-LAST:event_formPropertyChange

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        if(cmbPeople.getSelectedIndex()==0)
        {
            // get date from datepicker
            Date date1 = new Date(datePicker1.getText());
            SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
            String appDate = formatter.format(date1);
            System.out.println(appDate);
        
            // get time from timepicker
            String time = timePicker1.getText();
        
            // get center from combo box
            String center = cmbCenter.getSelectedItem().toString();
        
            //get details of vaccination center
            Vaccination_Center vacCenter = new Vaccination_Center();
        
            File file = new File("Vaccination_Center.txt");
            try
            {
                Scanner Sc = new Scanner(file);
                while(Sc.hasNext())
                {
                    String Line = Sc.nextLine();
                    String[] Arr = Line.split(";");
                    if(center.equals(Arr[1]))
                    {
                        vacCenter.setCode(Arr[0]);
                        vacCenter.setName(Arr[1]);
                        vacCenter.setAddress(Arr[2]);
                        vacCenter.setVac(new Vaccines(Arr[3],Arr[4]));
                    }
                    System.out.println("Found");
                    System.out.println(vacCenter);
                }
            }   
            catch(FileNotFoundException ex)
            {
            
            }
        
            DefaultTableModel model = (DefaultTableModel)tblPeople.getModel();
            int SelRow = tblPeople.getSelectedRow();
            String isNull = model.getValueAt(SelRow, 6).toString();
        
            if(isNull.equals("null"))
            {
                Appointment1 app1 = new Appointment1(appDate,time);
                app1.setVacCenter(vacCenter);
                
                model.setValueAt(app1.getAppointmentDate(),SelRow,6);
                model.setValueAt(app1.getAppointmentTime(),SelRow,7);
                //model.setValueAt(myData[1],SelRow,1);
                //model.setValueAt(myData[2],SelRow,2);
                //model.setValueAt(myData[3],SelRow,3);
                //model.setValueAt(myData[4],SelRow,4);
                //model.setValueAt(myData[5],SelRow,5);
            
                Citizens C1 = new Citizens(model.getValueAt(SelRow, 0).toString(),
                model.getValueAt(SelRow, 1).toString(), 
                model.getValueAt(SelRow, 2).toString(), 
                model.getValueAt(SelRow, 3).toString(), 
                model.getValueAt(SelRow, 4).toString(), app1);
            
                System.out.println(C1.toString3());
        
                FileOperation Fop = new FileOperation();
                Fop.ModifyTextFile("Citizens.txt", SelRow, C1.toString3());
            }
            else if(model.getValueAt(SelRow, 14).toString().equals("null"))
            {
                String appDate1 = model.getValueAt(SelRow, 6).toString();
                String appTime1 = model.getValueAt(SelRow, 7).toString();
                Vaccination_Center vacCenter1 = new Vaccination_Center(model.getValueAt(SelRow, 8).toString(), 
                        model.getValueAt(SelRow, 9).toString(), model.getValueAt(SelRow, 10).toString(), 
                        model.getValueAt(SelRow, 11).toString(), model.getValueAt(SelRow, 12).toString());
                
                Appointment2 app2 = new Appointment2(appDate1,appTime1,vacCenter1,appDate,time);
                app2.setVacCenter(vacCenter);
                
                model.setValueAt(app2.getAppointmentDate(),SelRow,15);
                model.setValueAt(app2.getAppointmentTime(),SelRow,16);
                //model.setValueAt(myData[1],SelRow,1);
                //model.setValueAt(myData[2],SelRow,2);
                //model.setValueAt(myData[3],SelRow,3);
                //model.setValueAt(myData[4],SelRow,4);
                //model.setValueAt(myData[5],SelRow,5);
            
                Citizens C1 = new Citizens(model.getValueAt(SelRow, 0).toString(),
                model.getValueAt(SelRow, 1).toString(), 
                model.getValueAt(SelRow, 2).toString(), 
                model.getValueAt(SelRow, 3).toString(), 
                model.getValueAt(SelRow, 4).toString(), app2);
            
                System.out.println(C1.toString2());
        
                FileOperation Fop = new FileOperation();
                Fop.ModifyTextFile("Citizens.txt", SelRow, C1.toString2());
            }
        }
   
        if(cmbPeople.getSelectedIndex()==1)
        {
            // get date from datepicker
            Date date1 = new Date(datePicker1.getText());
            SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
            String appDate = formatter.format(date1);
            System.out.println(appDate);
        
            // get time from timepicker
            String time = timePicker1.getText();
        
            // get center from combo box
            String center = cmbCenter.getSelectedItem().toString();
        
            //get details of vaccination center
            Vaccination_Center vacCenter = new Vaccination_Center();
        
            File file = new File("Vaccination_Center.txt");
            try
            {
                Scanner Sc = new Scanner(file);
                while(Sc.hasNext())
                {
                    String Line = Sc.nextLine();
                    String[] Arr = Line.split(";");
                    if(center.equals(Arr[1]))
                    {
                        vacCenter.setCode(Arr[0]);
                        vacCenter.setName(Arr[1]);
                        vacCenter.setAddress(Arr[2]);
                        vacCenter.setVac(new Vaccines(Arr[3],Arr[4]));
                    }
                    System.out.println("Found");
                    System.out.println(vacCenter);
                }
            }   
            catch(FileNotFoundException ex)
            {
            
            }
        
            DefaultTableModel model = (DefaultTableModel)tblPeople.getModel();
            int SelRow = tblPeople.getSelectedRow();
            String isNull = model.getValueAt(SelRow, 6).toString();
        
            if(isNull.equals("null"))
            {
                Appointment1 app1 = new Appointment1(appDate,time);
                app1.setVacCenter(vacCenter);
                
                model.setValueAt(app1.getAppointmentDate(),SelRow,6);
                model.setValueAt(app1.getAppointmentTime(),SelRow,7);
                //model.setValueAt(myData[1],SelRow,1);
                //model.setValueAt(myData[2],SelRow,2);
                //model.setValueAt(myData[3],SelRow,3);
                //model.setValueAt(myData[4],SelRow,4);
                //model.setValueAt(myData[5],SelRow,5);
            
                Citizens C1 = new Citizens(model.getValueAt(SelRow, 0).toString(),
                model.getValueAt(SelRow, 1).toString(), 
                model.getValueAt(SelRow, 2).toString(), 
                model.getValueAt(SelRow, 3).toString(), 
                model.getValueAt(SelRow, 4).toString(), app1);
            
                System.out.println(C1.toString3());
        
                FileOperation Fop = new FileOperation();
                Fop.ModifyTextFile("NonCitizens.txt", SelRow, C1.toString3());
            }
            else if(model.getValueAt(SelRow, 14).toString().equals("null"))
            {
                String appDate1 = model.getValueAt(SelRow, 6).toString();
                String appTime1 = model.getValueAt(SelRow, 7).toString();
                Vaccination_Center vacCenter1 = new Vaccination_Center(model.getValueAt(SelRow, 8).toString(), 
                        model.getValueAt(SelRow, 9).toString(), model.getValueAt(SelRow, 10).toString(), 
                        model.getValueAt(SelRow, 11).toString(), model.getValueAt(SelRow, 12).toString());
                
                Appointment2 app2 = new Appointment2(appDate1,appTime1,vacCenter1,appDate,time);
                app2.setVacCenter(vacCenter);
                
                model.setValueAt(app2.getAppointmentDate(),SelRow,15);
                model.setValueAt(app2.getAppointmentTime(),SelRow,16);
                //model.setValueAt(myData[1],SelRow,1);
                //model.setValueAt(myData[2],SelRow,2);
                //model.setValueAt(myData[3],SelRow,3);
                //model.setValueAt(myData[4],SelRow,4);
                //model.setValueAt(myData[5],SelRow,5);
            
                Citizens C1 = new Citizens(model.getValueAt(SelRow, 0).toString(),
                model.getValueAt(SelRow, 1).toString(), 
                model.getValueAt(SelRow, 2).toString(), 
                model.getValueAt(SelRow, 3).toString(), 
                model.getValueAt(SelRow, 4).toString(), app2);
            
                System.out.println(C1.toString2());
        
                FileOperation Fop = new FileOperation();
                Fop.ModifyTextFile("NonCitizens.txt", SelRow, C1.toString2());
            }
        }
   
    }//GEN-LAST:event_btnAddActionPerformed

    private void cmbPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPeopleActionPerformed
        
        DefaultTableModel model = (DefaultTableModel)tblPeople.getModel();
        model.setNumRows(0);
        
        if(cmbPeople.getSelectedIndex()==0)
        {
            File file = new File("Citizens.txt");     
        
            try
            {
                Scanner Sc = new Scanner(file);
                while(Sc.hasNext())
                {
                    String[] line = Sc.nextLine().split(";");
                    model.addRow(line);
                }
            }
            catch(FileNotFoundException ex)
            {
            
            }   
        }
        else if(cmbPeople.getSelectedIndex()==1)
        {
            File file = new File("NonCitizens.txt");     
        
            try
            {
                Scanner Sc = new Scanner(file);
                while(Sc.hasNext())
                {
                    String[] line = Sc.nextLine().split(";");
                    model.addRow(line);
                }
            }
            catch(FileNotFoundException ex)
            {
            
            }   
        }
    }//GEN-LAST:event_cmbPeopleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Appointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cmbCenter;
    private javax.swing.JComboBox<String> cmbPeople;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPeople;
    private com.github.lgooddatepicker.components.TimePicker timePicker1;
    // End of variables declaration//GEN-END:variables
}
