/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Assign_Vaccines extends javax.swing.JFrame {

    /**
     * Creates new form Assign_Vaccines
     */
    public Assign_Vaccines() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVaccines = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCenter = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Assign Vaccines to Vaccination Center");

        tblVaccines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Name", "Vaccine Batch"
            }
        ));
        jScrollPane1.setViewportView(tblVaccines);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Please select a vaccine:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Please select a Vaccination Center:");

        tblCenter.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblCenter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccination Center Code", "Vaccination Center Name", "Vaccination Center Address", "Vaccine", "Batch"
            }
        ));
        jScrollPane4.setViewportView(tblCenter);

        btnAssign.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnAssign.setText("Assign Vaccines");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnRemove.setText("Remove Assignment");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnModify.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnModify.setText("Modify Assignment");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnView.setText("View Assignment");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnSearch.setText("Search Assignment");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Search Here:");

        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(136, 136, 136)
                        .addComponent(btnBack)
                        .addGap(52, 52, 52))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(42, 42, 42)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAssign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(61, 76, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnAssign)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnRemove)
                        .addGap(18, 18, 18)
                        .addComponent(btnModify)
                        .addGap(18, 18, 18)
                        .addComponent(btnView)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        
        //Display vaccines 
        DefaultTableModel modelVac = (DefaultTableModel)tblVaccines.getModel();
        modelVac.setNumRows(0);
        File file = new File("Vaccines.txt");
        
        try
        {
            Scanner Sc = new Scanner(file);
            while(Sc.hasNext())
            {
                String[] line = Sc.nextLine().split(";");
                modelVac.addRow(line);
            }
        }
        catch(FileNotFoundException ex)
        {
            
        }
        
        //Display Vaccination Center
        DefaultTableModel modelCenter = (DefaultTableModel)tblCenter.getModel();
        modelCenter.setNumRows(0);
        File file1 = new File("Vaccination_Center.txt");
        
        try
        {
            Scanner Sc = new Scanner(file1);
            while(Sc.hasNext())
            {
                String[] line = Sc.nextLine().split(";");
                modelCenter.addRow(line);
            }
        }
        catch(FileNotFoundException ex)
        {
            
        }
    }//GEN-LAST:event_formPropertyChange

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        
        if(tblVaccines.getSelectionModel().isSelectionEmpty() && tblCenter.getSelectionModel().isSelectionEmpty())
        {
              JOptionPane.showOptionDialog(null, "Please select a vaccine and vaccination center!!! ", "Reminder", JOptionPane.OK_CANCEL_OPTION, 
                JOptionPane.INFORMATION_MESSAGE, null, null, null);
        }
        else if(tblVaccines.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showOptionDialog(null, "Please select a vaccine!!! ", "Reminder", JOptionPane.OK_CANCEL_OPTION, 
                JOptionPane.INFORMATION_MESSAGE, null, null, null);
        }
        else if(tblCenter.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showOptionDialog(null, "Please select a vaccination center!!! ", "Reminder", JOptionPane.OK_CANCEL_OPTION, 
                JOptionPane.INFORMATION_MESSAGE, null, null, null);
        }
        else
        {
            DefaultTableModel modelVac = (DefaultTableModel)tblVaccines.getModel();
            int SelRowVac = tblVaccines.getSelectedRow();
            Vaccines vac = new Vaccines(modelVac.getValueAt(SelRowVac, 0).toString(), modelVac.getValueAt(SelRowVac, 1).toString());
        
            DefaultTableModel modelCenter = (DefaultTableModel)tblCenter.getModel();
            int SelRowCenter = tblCenter.getSelectedRow();
            Vaccination_Center vacCenter = new Vaccination_Center(modelCenter.getValueAt(SelRowCenter, 0).toString(),
                    modelCenter.getValueAt(SelRowCenter, 1).toString(), modelCenter.getValueAt(SelRowCenter, 2).toString(),vac);
                
            modelCenter.setValueAt(vac.getName(), SelRowCenter, 3);
            modelCenter.setValueAt(vac.getBatch(), SelRowCenter, 4);
        
            System.out.println(vacCenter.toString());
        
            FileOperation Fop = new FileOperation();
            Fop.ModifyTextFile("Vaccination_Center.txt", SelRowCenter, vacCenter.toString());
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        
        if(tblCenter.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showOptionDialog(null, "Please select a vaccination center!!! ", "Reminder", JOptionPane.OK_CANCEL_OPTION, 
                JOptionPane.INFORMATION_MESSAGE, null, null, null);
        }
        else
        {
            DefaultTableModel modelCenter = (DefaultTableModel)tblCenter.getModel();
            int SelRowCenter = tblCenter.getSelectedRow();
            Vaccination_Center vacCenter = new Vaccination_Center(modelCenter.getValueAt(SelRowCenter, 0).toString(),
                    modelCenter.getValueAt(SelRowCenter, 1).toString(), modelCenter.getValueAt(SelRowCenter, 2).toString(),null,null);
            
            modelCenter.setValueAt("null", SelRowCenter, 3);
            modelCenter.setValueAt("null", SelRowCenter, 4);
            
            System.out.println(vacCenter.toString());
        
            FileOperation Fop = new FileOperation();
            Fop.ModifyTextFile("Vaccination_Center.txt", SelRowCenter, vacCenter.toString());
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        
        DefaultTableModel modelVac = (DefaultTableModel)tblVaccines.getModel();
        int SelRowVac = tblVaccines.getSelectedRow();
        DefaultTableModel modelCenter = (DefaultTableModel)tblCenter.getModel();
        int SelRowCenter = tblCenter.getSelectedRow();
        
        if(tblVaccines.getSelectionModel().isSelectionEmpty() && tblCenter.getSelectionModel().isSelectionEmpty())
        {
              JOptionPane.showOptionDialog(null, "Please select a vaccine and vaccination center!!! ", "Reminder", JOptionPane.OK_CANCEL_OPTION, 
                JOptionPane.INFORMATION_MESSAGE, null, null, null);
        }
        else if(tblVaccines.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showOptionDialog(null, "Please select a vaccine!!! ", "Reminder", JOptionPane.OK_CANCEL_OPTION, 
                JOptionPane.INFORMATION_MESSAGE, null, null, null);
        }
        else if(tblCenter.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showOptionDialog(null, "Please select a vaccination center!!! ", "Reminder", JOptionPane.OK_CANCEL_OPTION, 
                JOptionPane.INFORMATION_MESSAGE, null, null, null);
        }
        else if(modelCenter.getValueAt(SelRowCenter, 3).toString().equals("null"))
        {
            JOptionPane.showOptionDialog(null, "No vaccine can be modified!!! ", "Reminder", JOptionPane.OK_CANCEL_OPTION, 
                JOptionPane.INFORMATION_MESSAGE, null, null, null);
        }
        else
        {       
            Vaccines vac = new Vaccines(modelVac.getValueAt(SelRowVac, 0).toString(), modelVac.getValueAt(SelRowVac, 1).toString());
            Vaccination_Center vacCenter = new Vaccination_Center(modelCenter.getValueAt(SelRowCenter, 0).toString(),
                modelCenter.getValueAt(SelRowCenter, 1).toString(), modelCenter.getValueAt(SelRowCenter, 2).toString(),vac);
              
            modelCenter.setValueAt(vac.getName(), SelRowCenter, 3);
            modelCenter.setValueAt(vac.getBatch(), SelRowCenter, 4);
        
            System.out.println(vacCenter.toString());
        
            FileOperation Fop = new FileOperation();
            Fop.ModifyTextFile("Vaccination_Center.txt", SelRowCenter, vacCenter.toString());
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        
        DefaultTableModel model = (DefaultTableModel)tblCenter.getModel();
        model.setNumRows(0);
        
        File file = new File("Vaccination_Center.txt");     
        
            try
            {
                Scanner Sc = new Scanner(file);
                while(Sc.hasNext())
                {
                    String[] line = Sc.nextLine().split(";");
                    model.addRow(line);
                }
            }
            catch(FileNotFoundException ex)
            {
            
            }   
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        DefaultTableModel model = (DefaultTableModel)tblCenter.getModel();
        model.setNumRows(0);
        
        File file = new File("Vaccination_Center.txt");     
        
            try
            {
                Scanner Sc = new Scanner(file);
                while(Sc.hasNext())
                {
                    String[] line = Sc.nextLine().split(";");
                    
                    if(line[0].equals(txtSearch.getText()) || line[1].equals(txtSearch.getText()) || 
                            line[2].equals(txtSearch.getText()) || line[3].equals(txtSearch.getText()) || 
                            line[4].equals(txtSearch.getText()))
                    {
                        model.addRow(line);
                    }
                }
            }
            catch(FileNotFoundException ex)
            {
            
            } 
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        JOptionPane.showMessageDialog(null,"Manage Vaccination Center and The Supply of Covid19 Vaccines ???");
        this.dispose();    //hide the login form after validated
        Vaccines_Center vac_Center = new Vaccines_Center();        //go to another frame
        vac_Center.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assign_Vaccines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assign_Vaccines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assign_Vaccines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assign_Vaccines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assign_Vaccines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblCenter;
    private javax.swing.JTable tblVaccines;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
